### ISSUE TITLE
Retrieving audio URL does not work for all types of Pandora clients

### ISSUE THREAD

**Issue by jcass77** [mcrute/pydora#1]
The ```audioUrl``` field in [pandora.py](https://github.com/mcrute/pydora/blob/3124125ebdba337c22dfb84f2c29151e8cbc105f/pandora/models/pandora.py#L27-38) does not map correctly for all partner device types. 

```python
class PlaylistItem(PandoraModel):

    artist_name = Field('artistName')
    album_name = Field('albumName')
    song_name = Field('songName')
    song_rating = Field('songRating')
    track_gain = Field('trackGain')
    track_token = Field('trackToken')
    audio_url = Field('audioUrl')
    album_art_url = Field('albumArtUrl')
    allow_feedback = Field('allowFeedback', True)
    station_id = Field('stationId')
```

For example, for **android-generic** the actual URL is stored in a dictionary with structure:

```[audioUrlMap][xQuality][audioUrl]``` where x is either 'low', 'medium', or 'high'.

This error can be reproduced by setting ```partner_device = android-generic``` in ~/.pydora.cfg and updating the related configuration entries for encryption etc. as per the [unofficial Pandora API](http://6xq.net/playground/pandora-apidoc/json/partners/#partners)

I'm not sure whether it would be better to make ```PlayListItem``` partner-type aware based on some user-specified preferred bitrate in the configuration files, or if the loop in 'from_json' should just fall back to trying to retrieve the highest available stream:

https://github.com/mcrute/pydora/blob/1e8502b1eabb8e595f1f23d26e62d7763097b2a0/pandora/models/__init__.py#L51-63

**Comment by mcrute** [comment]
Merged and release 0.2.3 to pypi. Thanks for the patch!
