### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED error on login

### ISSUE THREAD

**Issue by jcass77** [mcrute/pydora#27]
Pandora changed the certificates for the Pandora One ```api_host``` (internal-tuner.pandora.com/services/json/) about a week ago:

```
ERROR    2015-11-12 12:00:40,096 [77037:PandoraBackend-8] mopidy_pandora.uri
  Error logging in to Pandora: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
INFO     2015-11-12 12:00:40,096 [77037:MainThread] mopidy.commands
```

This issue has popped up on all of the other Pandora players as well (https://github.com/pithos/pithos/issues/251, https://github.com/PromyLOPh/pianobar/issues/555). Various workarounds have been suggested, from ignoring certificates to reverting to using curl.

PIP reports that I have ```certifi (2015.4.28)``` installed, if that is relevant. In the interim, relying on ```tuner.pandora.com/services/json/``` still works but obviously won't have the high-quality Pandora One stream available.

Not sure how to address this in pydora at this stage...any ideas?

**Comment by mcrute** [comment]
It looks like they've mis-configured their servers. Running `openssl s_client -connect internal-tuner.pandora.com:443 -showcerts` shows only the server certificate and they should be distributing their intermediate certificate too. This fails for me on Ubuntu but not Mac OS. In the sort term we could distribute the Verisign intermediate certificate with pydora.

It's a bit hacky and ugly but should fix the problem for now.

**Comment by jcass77** [comment]
PandoraOne works again for me on Debian 7.8 and OSX 10.11.1 - maybe they fixed this on their side?

**Comment by jcass77** [comment]
...and for future reference, an example for distributing the intermediate certificate is contained over at https://github.com/pithos/pithos/commit/38d922e717fc141493c811e3658a07c355a71634

**Comment by mcrute** [comment]
It does look like they've fixed the mis-configuration on their side. I'm not keen on bundling their intermediate certs with pydora so I'm going to close this for now and we can re-visit if they break it again.
