### ISSUE TITLE
Player does not appear to work on OSX

### ISSUE THREAD

**Issue by jcass77** [mcrute/pydora#29]
I get the following stack trace as soon as a station is selected in the bundled player:

Traceback (most recent call last):
The Wishing Well  File "/usr/local/bin/pydora", line 9, in <module>
 by     load_entry_point('pydora==1.6', 'console_scripts', 'pydora')()
Sharon Shannon & Friends  File "/Users/jcass/PycharmProjects/Mopidy/pydora/pydora/player.py", line 199, in main

    PlayerApp().run()
  File "/Users/jcass/PycharmProjects/Mopidy/pydora/pydora/player.py", line 193, in run
    self.player.play_station(station)
  File "/Users/jcass/PycharmProjects/Mopidy/pydora/pydora/mpg123.py", line 97, in play_station
    self.play(song)
  File "/Users/jcass/PycharmProjects/Mopidy/pydora/pydora/mpg123.py", line 82, in play
    self._callbacks.post_poll()
  File "/Users/jcass/PycharmProjects/Mopidy/pydora/pydora/player.py", line 184, in post_poll
    Screen.set_echo(True)
  File "/Users/jcass/PycharmProjects/Mopidy/pydora/pydora/utils.py", line 44, in set_echo
    lflag, ispeed, ospeed, cc) = termios.tcgetattr(fd)
termios.error: (25, 'Inappropriate ioctl for device')

**Comment by mcrute** [comment]
What does your runtime setup look like? I often use the CLI player on Mac OS on Python 2 and 3 under the default terminal and haven't run into this issue.

I'm happy to merge #30 but would like to try to reproduce the issue so I can write a test for it to prevent future regressions.

**Comment by jcass77** [comment]
OSX 10.11.1, Python 2.7, standard terminal - anything else that could be relevant?

**Comment by jcass77** [comment]
I think this is related to the version of Xcode and the command line tools that are installed.

I had Xcode 6.1.1 but never opened the application before, so the optional command line and debug tools were not installed. Doing that seems to have fixed the problem.

So if that is the case the question is whether the pydora player should be dependant on Xcode?

**Comment by mcrute** [comment]
The player should not require Xcode. Merging #30
