### ISSUE TITLE
Ads fail to register if tracking_tokens are missing

### ISSUE THREAD

**Issue by jcass77** [mcrute/pydora#39]
I've been encountering random issues with some advertisements not registering properly (see [#37](https://github.com/rectalogic/mopidy-pandora/issues/37) at the Mopidy-Pandora project for stack trace details).

As best as I can tell, this happens if the advertisement does not contain any add tracking tokens (maybe one in every five ads being served up), causing ```APIClient.register_ad(station_id, tokens)``` to raise a ```ParameterMissing``` exception.

**Comment by mcrute** [comment]
Merged #37
