### ISSUE TITLE
Remove `py_release_tools` from `setup_requires` or provide wheels

### ISSUE THREAD

**Issue by t-8ch** [mcrute/pydora#46]
Currently installing pydora from PyPI fails because `py_release_tools` pulls in `mock` which has a broken `setup.cfg`.
OTOH my music machine does not need the dev-dependencies. There are two (non-exclusive) ways out of this:
* Provide wheels on PyPI. I won't ever have to evaluate setup.py
* Make the dependency on `py_release_tools` optional by looking at `sys.argv` and decide based on that.

Thanks for considering.

**Comment by mcrute** [comment]
I think the best approach would be to provide wheels given that's the preferred packaging format for Python these days. I'll see if I can make that part of the build process and push them to PyPi today.

**Comment by mcrute** [comment]
Fixed in d16320a. I updated [1.7.3](https://pypi.python.org/pypi/pydora/1.7.3) with a wheel. Let me know if this fixes the issue you're experiencing.

**Comment by t-8ch** [comment]
Unfortunately pip does not pick up the wheel.
The only difference I can see to working wheels is that `pydora-1.7.3-py2.py3-none-any.whl` has `Py version: any` on PyPI while for example ` wheel-0.29.0-py2.py3-none-any.whl ` and `jiffybox-0.11.0-py2.py3-none-any.whl` have `py2.py3`.

Weirdly enough `requests-2.10.0-py2.py3-none-any.whl` has only `py2` but also works on py3...

**Comment by t-8ch** [comment]
https://pypi.python.org/simple/pydora/ shows that the sdist for 1.7.3 is actually called `1.7.3-1`, so this may be the problem.

**Comment by mcrute** [comment]
Apparently files uploaded to pypi are immutable so I created another release [1.7.5](https://pypi.python.org/pypi/pydora/1.7.5) which has the same format as requests. Please try that and let me know if it fixes the problem.

**Comment by t-8ch** [comment]
@mcrute Now it works. Thank you!
