### ISSUE TITLE
Broken pipe on play station

### ISSUE THREAD

**Issue by partofthething** [mcrute/pydora#47]
I just installed pydora and may have missed something. I'm on a Raspberry Pi 2 under Debian Jessie using Python 3.4.2. 

When I try to play a station, it fails immediately with this traceback. Is this maybe related to that warning in the Python docs about not eading/writing to subprocess pipes due to race conditions or something?
```
...
 29: electro-pop-dance-rock
Station: 1
Judge Me by Sia
Traceback (most recent call last):
  File "/usr/local/bin/pydora", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/pydora/player.py", line 199, in main
    PlayerApp().run()
  File "/usr/local/lib/python3.4/dist-packages/pydora/player.py", line 193, in run
    self.player.play_station(station)
  File "/usr/local/lib/python3.4/dist-packages/pydora/mpg123.py", line 97, in play_station
    self.play(song)
  File "/usr/local/lib/python3.4/dist-packages/pydora/mpg123.py", line 63, in play
    self._send_cmd("load {}".format(song.audio_url))
  File "/usr/local/lib/python3.4/dist-packages/pydora/mpg123.py", line 39, in _send_cmd
    self._process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by mcrute** [comment]
This sounds a lot like the mpg123 process is dying (or failed to start) more than a race condition. It should be pretty easy to test this, if you start the pydora cli you should be able to run `pgrep -l mpg123` in another shell and see that mpg123 is running, if not that would cause this error. Otherwise I could create debug build that writes an error log, the CLI discards the mpg123 stderr by default.

You do bring up a good point about process management and error handling in the cli, it's a bit sloppy. I'll work on cleaning that up for a future release.

**Comment by partofthething** [comment]
I confirmed that `mpg123` is indeed running when I first fire up pydora but as soon as I choose a station I get this traceback and mpg123 ends with it. I also confirmed that mpg123 works if I run it on a random file. Some debug info from mpg123 would be nice for sure. 

The standalone `mpg123` run does show some ALSA warnings but they don't prevent sound from playing: 

```
MPEG 1.0 layer III, 128 kbit/s, 44100 Hz stereo
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front                                                            
```

**Comment by partofthething** [comment]
I was able to get around the broken pipe by changing line 21 of `mpg123.py` to

```python
["mpg123", "-q", "-R", "--ignore-mime", '.'])
```
Without the `.` it just closes when I run on the command line (but strangely the pgrep still showed it there...). So then I was able to get a station up and running!

**Comment by mcrute** [comment]
Okay, I'll test out adding the dot and the signals cleanup this weekend and try to get a release out if everything works.

**Comment by mcrute** [comment]
Sorry for the delay, I've applied the fix and it seems to work so it will be released later today.
