### ISSUE TITLE
Becoming an approved pandora developer

### ISSUE THREAD

**Issue by CrawFishFiesta** [mcrute/pydora#50]
This isn't really an issue, but does anyone know how to become an approved pandora developer to use the official pandora API?

Thanks.

**Comment by mcrute** [comment]
This is an unofficial API client. You should be able to use it to get up and running with your project. If you need something more than that you should get in touch with Pandora directly. While this project makes use of Pandora it is not affiliated with Pandora in any way.

**Comment by CrawFishFiesta** [comment]
Does your pydora API module allow some to decode a pandora track_id to
obtain song and artist information?

Thanks for your time.

Calvin.
