### ISSUE TITLE
PyDora pydora-configure configuration script error

### ISSUE THREAD

**Issue by SlimyFrog123** [mcrute/pydora#68]
**What happened**: I installed pydora and ran the pydora-configure function, but it gave me this error: Error loading config file. Unable to continue.
![Screenshot 2021-09-01 175545](https://user-images.githubusercontent.com/89934852/131765041-0019820b-05ae-4229-8bac-d13215f08b22.png)

**Environment**:
- Pydora version: 2.1.0
- Python version: 3.7.8 64-bit
- OS: Windows 10 64 bit

**Comment by mcrute** [comment]
It looks like the config file format changed slightly as did the location. [2.1.1](https://pypi.org/project/pydora/2.1.1/) is released which fixes this.
